name: Linter

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
  workflow_dispatch:

jobs:
  selene:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint source with Selene
        uses: YoloWingPixie/selene-lua-linter-action@v1
        with:
          config-path: 'selene.toml'
          lint-path: 'src/'
