name: Test Release

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - test-release

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || (github.event.pull_request.merged == true && github.event.pull_request.head.ref != 'main')
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v1

      - run: bun install

      - name: Build with Rojo
        run: rojo build -o LightBorn.rbxm

      - name: Release with semantic-release
        run: bunx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
